### ISSUE TITLE
No Schema when loading a XML-File in Default

### ISSUE THREAD

**Issue by rukichen** [olehmberg/winter#16]
When I try loading a XML in without making an extra model, like described in the documentation. There will not be a schema designed to the dataset. 
Loading itself works. You can access the data loaded in the dataset. I tried to find our what is going wrong.
When load a csv-file a schema is there. When constructing an extra model for the xml-File. The schema is there, too. 
When looking into the XMLMatchableReader there is a schema there for defaultLoading but it disappears when going back to the original starting class. 

That makes it impossible to use any matching tools.

**Comment by Alex0815** [comment]
Hey @rukichen,
can you provide a short code snippet?
Just to be sure that I understood your problem correctly.
Cheers

**Comment by olehmberg** [comment]
Hi @rukichen ,

I just checked the issue and XMLRecordReader did not add the attributes provided in the node mapping to the dataset. I fixed this for the development branch. If you need a workaround for the current release branch, just add the attributes to the dataset manually (using dataset.AddAttribute).

Cheers,
Oli

**Comment by rukichen** [comment]
Thanks a lot, yes I found out that this was the case, and added it. Now its working fine.
