### ISSUE TITLE
approximate FD by TANE

### ISSUE THREAD

**Issue by wunderbarr** [olehmberg/winter#37]
Hello,
Have you run your program to test the result of approximate FD? I generate same result as in the original paper if the error threshold is 0. But for the approximate FD result with error threshold 0.01, 0.05, etc, I cannot obtain same result as in the published experiment. Have you repeated the same experimental result for approximate FDs?
Thank you!

**Comment by olehmberg** [comment]
Hi wunderbarr,

thanks for pointing that out! I have replaced the implementation with a wrapper for the original TANE algorithm in commit 8c12689 in the development branch.
