### ISSUE TITLE
Handle Null values when performing Identity Resolution 

### ISSUE THREAD

**Issue by juriigen** [olehmberg/winter#41]
Hi ,
i want to perform some Identity Resolution where the entities have many attributes, but some of the attribute values can be null. Is there any way to handle this from winter ?

**Comment by olehmberg** [comment]
Hi @juriigen 

sure, this is possible. All you need to do is to make sure that your Comparators can handle null values, for example by returning a similarity of 0.0.

Please let me know if this answers your question, or if you have a specific problem (in which case it would help if you could provide a runnable code sample).
