### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by amin9565** [olehmberg/winter#43]
hello 
thank you for published this project.
where is inputs?
thank you in advanced.

**Comment by bizer** [comment]
Hello,
the inputs for the tutorial processes are found here:
https://github.com/olehmberg/winter/tree/master/winter-usecases/usecase/movie/input
Instructions on how to run the processes are found here:
https://github.com/olehmberg/winter/wiki/WInte.r-Tutorial
Best,
Christian Bizer
