### ISSUE TITLE
potential bug/error in RDFMatchableReader

### ISSUE THREAD

**Issue by jerrygaoLondon** [olehmberg/winter#7]
Main issue: From the example in 'RDFRecordReaderTest', it seems that the schema/attributes are incorrectly assigned.

Possible causes: As can be seen from the definition of abstract method readLine() in RDFMatchableReader , the the actual attribute is not passed to the dataset population method. In the implementation (RDFRecordReader class), attribute identifier looks fine, but the attribute value is assigned to the attribute name and the values are assigned again to the record. This seems not correct to me.

**Comment by olehmberg** [comment]
Hi Jerry,

Thanks for pointing that out. There was indeed a problem with the attributes. I fixed the problem and updated the test case to check for that problem in the future. 

Please let me know if you find any other issues.
